# 1.4.4 Smoothing Images

## Kernel Convolution

In [13]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [14]:
l=1
kernel = np.array([[0,-1,0],[-1,4,-1],[0,-1,0]],np.float32)

In [15]:
kernel

array([[ 0., -1.,  0.],
       [-1.,  4., -1.],
       [ 0., -1.,  0.]], dtype=float32)

In [16]:
img = np.random.randint(10, size=(12,12))
#img = np.ones((10,10),np.float32)

In [17]:
img

array([[9, 3, 7, 7, 7, 3, 6, 1, 8, 4, 3, 9],
       [0, 6, 6, 0, 2, 1, 6, 6, 3, 8, 9, 8],
       [8, 2, 7, 2, 5, 9, 2, 0, 5, 6, 1, 5],
       [8, 5, 4, 2, 2, 6, 3, 9, 1, 0, 9, 6],
       [0, 0, 3, 0, 1, 5, 1, 6, 5, 4, 6, 2],
       [7, 3, 9, 5, 9, 7, 9, 0, 6, 6, 2, 0],
       [2, 2, 7, 3, 2, 4, 0, 3, 0, 5, 5, 6],
       [8, 4, 8, 7, 0, 9, 7, 4, 7, 6, 6, 4],
       [2, 1, 2, 2, 0, 8, 3, 6, 8, 7, 2, 7],
       [8, 9, 1, 3, 5, 3, 4, 5, 9, 2, 3, 9],
       [1, 5, 3, 7, 2, 8, 1, 1, 7, 4, 2, 4],
       [3, 7, 7, 9, 0, 0, 6, 6, 9, 9, 1, 6]])

In [18]:
h,w=img.shape

In [19]:
print(h,w)

12 12


In [20]:
#[*range(-2,3)]

In [21]:
dst = np.zeros((h,w),dtype=int)

In [22]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i,j]=t        

In [23]:
img

array([[9, 3, 7, 7, 7, 3, 6, 1, 8, 4, 3, 9],
       [0, 6, 6, 0, 2, 1, 6, 6, 3, 8, 9, 8],
       [8, 2, 7, 2, 5, 9, 2, 0, 5, 6, 1, 5],
       [8, 5, 4, 2, 2, 6, 3, 9, 1, 0, 9, 6],
       [0, 0, 3, 0, 1, 5, 1, 6, 5, 4, 6, 2],
       [7, 3, 9, 5, 9, 7, 9, 0, 6, 6, 2, 0],
       [2, 2, 7, 3, 2, 4, 0, 3, 0, 5, 5, 6],
       [8, 4, 8, 7, 0, 9, 7, 4, 7, 6, 6, 4],
       [2, 1, 2, 2, 0, 8, 3, 6, 8, 7, 2, 7],
       [8, 9, 1, 3, 5, 3, 4, 5, 9, 2, 3, 9],
       [1, 5, 3, 7, 2, 8, 1, 1, 7, 4, 2, 4],
       [3, 7, 7, 9, 0, 0, 6, 6, 9, 9, 1, 6]])

In [24]:
dst

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,  13,   4, -17,  -5, -16,   9,  14, -15,  10,  16,   0],
       [  0, -18,  14,  -6,   5,  22, -10, -22,  10,  10, -25,   0],
       [  0,   6,  -1,   0,  -6,   5,  -6,  26, -15, -20,  23,   0],
       [  0, -11,  -1, -11, -12,   5, -19,   9,   3,  -1,   7,   0],
       [  0,  -6,  18,  -1,  21,   1,  28, -24,  13,   7,  -9,   0],
       [  0,  -8,   6,  -9,  -8,  -2, -23,   8, -21,   3,   1,   0],
       [  0,  -3,  12,  15, -18,  17,  12,  -7,  10,  -1,   7,   0],
       [  0, -13,  -4,  -4, -15,  17, -13,   4,   3,  10, -15,   0],
       [  0,  21, -13,  -3,  12, -13,   4,   0,  14, -15,  -3,   0],
       [  0,   0,  -8,  11, -12,  26, -15, -15,   5,  -4,  -4,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

In [25]:
img = cv2.imread('lena.png', 0)

In [26]:
h,w=img.shape

In [27]:
dst = np.zeros((h-2*l,w-2*l),np.uint8)

In [28]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i-l,j-l]=t 

In [29]:
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()